version: "2"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      
  grafana:
    image: grafana/grafana
    ports: 
      - 3000:3000 