global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'monitoring'    
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s    
    static_configs:
      - targets: ['10.0.1.3:8080']